apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "mlflow-test"
spec:
  predictor:
    serviceAccountName: sa
    sklearn:
      storageUri: <model-uri> # Example - "https://<storage-account-name>.blob.core.windows.net/<container-name>/0/models/<unique-folder>/artifacts"
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "1"
          memory: "1Gi"