apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
type: Opaque
stringData:
    AZ_CLIENT_ID: <client-id>
    AZ_CLIENT_SECRET: <client-secret>
    AZ_SUBSCRIPTION_ID: <subscription-id>
    AZ_TENANT_ID: <tenant-id>